"use client"

import React from "react"
import { createContext, useContext, useEffect, useState } from "react"

type Language = "bg" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  bg: {
    // Navigation
    "nav.about": "За нас",
    "nav.services": "Услуги",
    "nav.industries": "Сфери",
    "nav.clients": "Клиенти",
    "nav.pricing": "Цени",
    "nav.contact": "Контакт",
    "nav.dashboard": "Табло",
    "nav.logout": "Изход",
    "nav.theme.dark": "Тъмна тема",
    "nav.theme.light": "Светла тема",
    "nav.language": "Език",
    
    // Dashboard
    "dashboard.title": "Табло за управление",
    "dashboard.conversations": "Общо разговори с AI",
    "dashboard.hours": "Спестени часове",
    "dashboard.efficiency": "Увеличена ефективност",
    "dashboard.welcome": "Добре дошли",
    "dashboard.role.admin": "Администратор",
    "dashboard.role.client": "Клиент",
    
    // Hero
    "hero.badge": "AI Гласови Асистенти",
    "hero.title": "Дай глас на своя",
    "hero.titleHighlight": "бизнес",
    "hero.titleEnd": "с изкуствен интелект",
    "hero.description": "Създаваме персонализирани гласови AI асистенти, които работят 24/7, говорят като хора и повишават ефективността на твоя бизнес.",
    "hero.cta": "Да започваме",
    "hero.stat1": "24/7",
    "hero.stat1Label": "Денонощна работа",
    "hero.stat2": "-40%",
    "hero.stat2Label": "По-ниски разходи",
    "hero.stat3": "+60%",
    "hero.stat3Label": "Повече клиенти",
    
    // About
    "about.title": "За",
    "about.titleHighlight": "нас",
    "about.subtitle": "Създаваме решения с изкуствен интелект за реални компании",
    "about.mission.title": "Нашата мисия",
    "about.mission.text": "Да направим комуникацията между хора и технологии естествена и достъпна за всеки бизнес.",
    "about.team.title": "Нашият екип",
    "about.team.text": "Специалисти в AI технологии, гласови интерфейси и автоматизация на бизнес процеси.",
    "about.vision.title": "Нашата визия",
    "about.vision.text": "Всяка компания да има достъп до персонализиран AI асистент, който работи 24/7.",
    "about.story.title": "Нашата история",
    "about.story.text1": "Започнахме с идеята да направим гласовите AI асистенти достъпни за малките и средни бизнеси. Днес работим с водещи компании в различни индустрии и помагаме да автоматизират клиентското си обслужване.",
    "about.story.text2": "Нашите решения са помогнали на стотици компании да намалят разходите си с до 40% и да обслужват повече клиенти с по-високо качество.",
    
    // Services
    "services.title": "Нашите",
    "services.titleHighlight": "услуги",
    "services.subtitle": "Пълен пакет от AI решения за автоматизация на вашия бизнес",
    "services.voice.title": "Гласови AI асистенти",
    "services.voice.description": "Автоматизирани обаждания, резервации и клиентско обслужване 24/7 с естествен човешки глас.",
    "services.voice.f1": "Автоматични обаждания",
    "services.voice.f2": "Резервации и записвания",
    "services.voice.f3": "Клиентска поддръжка",
    "services.voice.f4": "Многоезична поддръжка",
    "services.chat.title": "Чатботи с естествен език",
    "services.chat.description": "Интелигентни текстови асистенти за сайтове, социални мрежи и месинджъри.",
    "services.chat.f1": "Facebook Messenger",
    "services.chat.f2": "WhatsApp интеграция",
    "services.chat.f3": "Уеб чат",
    "services.chat.f4": "Instagram DM",
    "services.integration.title": "Интеграции",
    "services.integration.description": "Свързване с вашите съществуващи системи за безпроблемна автоматизация.",
    "services.integration.f1": "CRM системи",
    "services.integration.f2": "ERP софтуер",
    "services.integration.f3": "Календари",
    "services.integration.f4": "Телефонни централи",
    "services.analytics.title": "AI анализ и отчетност",
    "services.analytics.description": "Проследяване на ефективността и детайлни отчети за всяко взаимодействие.",
    "services.analytics.f1": "Real-time статистики",
    "services.analytics.f2": "Анализ на разговори",
    "services.analytics.f3": "ROI отчети",
    "services.analytics.f4": "Sentiment анализ",
    
    // Industries
    "industries.title": "Сфери на",
    "industries.titleHighlight": "приложение",
    "industries.subtitle": "Нашите AI асистенти работят успешно в различни индустрии",
    "industries.restaurant.title": "Ресторанти",
    "industries.restaurant.description": "Автоматични резервации, поръчки и клиентско обслужване",
    "industries.restaurant.demo": "Здравейте! Бих искал да резервирам маса за 4-ма души...",
    "industries.salon.title": "Фризьорски салон",
    "industries.salon.description": "Записвания за пострижка, напомняния и информация",
    "industries.salon.demo": "Добър ден, искам да запиша час при Данката...",
    "industries.shop.title": "Онлайн магазини",
    "industries.shop.description": "Поддръжка на клиенти, проследяване на поръчки",
    "industries.shop.demo": "Здравейте, имам въпрос относно моята поръчка...",
    "industries.hotel.title": "Хотели",
    "industries.hotel.description": "Резервации, рецепция и консиерж услуги",
    "industries.hotel.demo": "Искам да резервирам стая за периода 15-20 юни...",
    "industries.corporate.title": "Корпоративна поддръжка",
    "industries.corporate.description": "Вътрешна комуникация и HR асистенти",
    "industries.corporate.demo": "Искам да подам заявка за отпуск...",
    
    // Case Studies
    "cases.title": "Истории на",
    "cases.titleHighlight": "успеха",
    "cases.subtitle": "Реални резултати от реални компании",
    "cases.costs": "Разходи",
    "cases.reservations": "Резервации",
    "cases.responseTime": "Време за отговор",
    "cases.clients": "Записани клиенти",
    "cases.missedCalls": "Пропуснати обаждания",
    "cases.satisfaction": "Удовлетвореност",
    "cases.sales": "Продажби",
    "cases.servedClients": "Обслужени клиенти",
    "cases.case1.company": "Ресторант \"Традиция\"",
    "cases.case1.industry": "Ресторантьорство",
    "cases.case1.description": "Автоматизирано приемане на резервации и отговаряне на въпроси 24/7",
    "cases.case2.company": "Фризьорски салон \"Luxury Hair\"",
    "cases.case2.industry": "Лични услуги",
    "cases.case2.description": "AI асистент за записване на часове и напомняния на клиенти",
    "cases.case3.company": "E-shop \"TechZone\"",
    "cases.case3.industry": "E-commerce",
    "cases.case3.description": "24/7 клиентска поддръжка и асистент за продажби",
    
    // Pricing
    "pricing.title": "Планове и",
    "pricing.titleHighlight": "цени",
    "pricing.subtitle": "Изберете плана, който отговаря на вашите нужди",
    "pricing.noFee": "Без начална такса",
    "pricing.guarantee": "30-дневна гаранция",
    "pricing.noContract": "Без обвързващ договор",
    "pricing.popular": "Най-популярен",
    "pricing.month": "месец",
    "pricing.starter.name": "Starter",
    "pricing.starter.description": "Идеален за малки бизнеси и стартъпи",
    "pricing.starter.f1": "До 1000 разговора месечно",
    "pricing.starter.f2": "Основни интеграции",
    "pricing.starter.f3": "Email поддръжка",
    "pricing.starter.f4": "Базов AI модел",
    "pricing.starter.f5": "1 гласов асистент",
    "pricing.starter.cta": "Започни сега",
    "pricing.pro.name": "Pro",
    "pricing.pro.description": "За растящи компании с високи изисквания",
    "pricing.pro.f1": "До 5000 разговора месечно",
    "pricing.pro.f2": "Всички интеграции",
    "pricing.pro.f3": "Приоритетна поддръжка",
    "pricing.pro.f4": "Персонализиран AI модел",
    "pricing.pro.f5": "До 3 гласови асистента",
    "pricing.pro.f6": "Advanced анализ",
    "pricing.pro.f7": "Custom гласове",
    "pricing.pro.cta": "Избери Pro",
    "pricing.enterprise.name": "Enterprise",
    "pricing.enterprise.description": "За големи корпорации и специални нужди",
    "pricing.enterprise.f1": "Неограничени разговори",
    "pricing.enterprise.f2": "Dedicated инфраструктура",
    "pricing.enterprise.f3": "24/7 техническа поддръжка",
    "pricing.enterprise.f4": "Custom AI обучение",
    "pricing.enterprise.f5": "Неограничени асистенти",
    "pricing.enterprise.f6": "White label решение",
    "pricing.enterprise.f7": "SLA гаранция",
    "pricing.enterprise.f8": "On-premise опция",
    "pricing.enterprise.cta": "Свържи се с нас",
    
    // Contact
    "contact.title": "Попитай ни",
    "contact.titleHighlight": "нещо",
    "contact.subtitle": "Разкажи ни за бизнеса си и ще ти създадем уникален AI глас",
    "contact.name": "Име и фамилия",
    "contact.namePlaceholder": "Иван Иванов",
    "contact.email": "Email",
    "contact.emailPlaceholder": "ivan@example.com",
    "contact.phone": "Телефон",
    "contact.phonePlaceholder": "+359 888 123 456",
    "contact.company": "Компания",
    "contact.companyPlaceholder": "Моята компания",
    "contact.message": "Разкажете за вашия бизнес",
    "contact.messagePlaceholder": "Опишете вашите нужди и как можем да ви помогнем...",
    "contact.submit": "Изпрати заявка",
    "contact.submitting": "Изпраща се...",
    "contact.success": "Успех!",
    "contact.error": "Грешка",
    "contact.errorMessage": "Възникна грешка при изпращането на заявката",
    "contact.emailLabel": "Email",
    "contact.phoneLabel": "Телефон",
    "contact.officeLabel": "Офис",
    "contact.workingHours": "Работно време",
    "contact.workingHoursText": "Понеделник - Петък: 9:00 - 18:00",
    "contact.aiWorkingHours": "AI асистентите работят 24/7",
    
    // Footer
    "footer.description": "Създаваме гласови AI асистенти, които работят 24/7 и говорят като хора.",
    "footer.products": "Продукти",
    "footer.voiceAssistants": "Гласови асистенти",
    "footer.chatbots": "Чатботи",
    "footer.integrations": "Интеграции",
    "footer.analytics": "Анализ",
    "footer.company": "Компания",
    "footer.aboutUs": "За нас",
    "footer.clients": "Клиенти",
    "footer.prices": "Цени",
    "footer.contacts": "Контакти",
    "footer.legal": "Правна информация",
    "footer.privacy": "Поверителност",
    "footer.terms": "Условия за ползване",
    "footer.gdpr": "GDPR",
    "footer.cookies": "Бисквитки",
    "footer.copyright": "© 2025 Voxal. Всички права запазени.",
  },
  en: {
    // Navigation
    "nav.about": "About",
    "nav.services": "Services",
    "nav.industries": "Industries",
    "nav.clients": "Clients",
    "nav.pricing": "Pricing",
    "nav.contact": "Contact",
    "nav.dashboard": "Dashboard",
    "nav.logout": "Logout",
    "nav.theme.dark": "Dark theme",
    "nav.theme.light": "Light theme",
    "nav.language": "Language",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.conversations": "Total AI Conversations",
    "dashboard.hours": "Hours Saved",
    "dashboard.efficiency": "Efficiency Increase",
    "dashboard.welcome": "Welcome",
    "dashboard.role.admin": "Administrator",
    "dashboard.role.client": "Client",
    
    // Hero
    "hero.badge": "AI Voice Assistants",
    "hero.title": "Give your",
    "hero.titleHighlight": "business",
    "hero.titleEnd": "a voice with artificial intelligence",
    "hero.description": "We create personalized AI voice assistants that work 24/7, speak like humans, and increase your business efficiency.",
    "hero.cta": "Let's get started",
    "hero.stat1": "24/7",
    "hero.stat1Label": "Round-the-clock service",
    "hero.stat2": "-40%",
    "hero.stat2Label": "Lower costs",
    "hero.stat3": "+60%",
    "hero.stat3Label": "More clients",
    
    // About
    "about.title": "About",
    "about.titleHighlight": "us",
    "about.subtitle": "We create AI solutions for real companies",
    "about.mission.title": "Our Mission",
    "about.mission.text": "To make communication between people and technology natural and accessible for every business.",
    "about.team.title": "Our Team",
    "about.team.text": "Specialists in AI technologies, voice interfaces, and business process automation.",
    "about.vision.title": "Our Vision",
    "about.vision.text": "Every company should have access to a personalized AI assistant that works 24/7.",
    "about.story.title": "Our Story",
    "about.story.text1": "We started with the idea to make voice AI assistants accessible to small and medium businesses. Today we work with leading companies in various industries and help automate their customer service.",
    "about.story.text2": "Our solutions have helped hundreds of companies reduce their costs by up to 40% and serve more customers with higher quality.",
    
    // Services
    "services.title": "Our",
    "services.titleHighlight": "services",
    "services.subtitle": "Complete package of AI solutions for automating your business",
    "services.voice.title": "Voice AI Assistants",
    "services.voice.description": "Automated calls, reservations, and 24/7 customer service with natural human voice.",
    "services.voice.f1": "Automatic calls",
    "services.voice.f2": "Reservations and bookings",
    "services.voice.f3": "Customer support",
    "services.voice.f4": "Multilingual support",
    "services.chat.title": "Natural Language Chatbots",
    "services.chat.description": "Intelligent text assistants for websites, social media, and messengers.",
    "services.chat.f1": "Facebook Messenger",
    "services.chat.f2": "WhatsApp integration",
    "services.chat.f3": "Web chat",
    "services.chat.f4": "Instagram DM",
    "services.integration.title": "Integrations",
    "services.integration.description": "Connect with your existing systems for seamless automation.",
    "services.integration.f1": "CRM systems",
    "services.integration.f2": "ERP software",
    "services.integration.f3": "Calendars",
    "services.integration.f4": "Phone exchanges",
    "services.analytics.title": "AI Analytics & Reporting",
    "services.analytics.description": "Track performance and detailed reports for every interaction.",
    "services.analytics.f1": "Real-time statistics",
    "services.analytics.f2": "Conversation analysis",
    "services.analytics.f3": "ROI reports",
    "services.analytics.f4": "Sentiment analysis",
    
    // Industries
    "industries.title": "Application",
    "industries.titleHighlight": "areas",
    "industries.subtitle": "Our AI assistants work successfully in various industries",
    "industries.restaurant.title": "Restaurants",
    "industries.restaurant.description": "Automatic reservations, orders, and customer service",
    "industries.restaurant.demo": "Hello! I would like to reserve a table for 4 people...",
    "industries.salon.title": "Hair Salon",
    "industries.salon.description": "Haircut appointments, reminders, and information",
    "industries.salon.demo": "Good day, I want to book an appointment with Dana...",
    "industries.shop.title": "Online Stores",
    "industries.shop.description": "Customer support, order tracking",
    "industries.shop.demo": "Hello, I have a question about my order...",
    "industries.hotel.title": "Hotels",
    "industries.hotel.description": "Reservations, reception, and concierge services",
    "industries.hotel.demo": "I want to book a room for June 15-20...",
    "industries.corporate.title": "Corporate Support",
    "industries.corporate.description": "Internal communication and HR assistants",
    "industries.corporate.demo": "I want to submit a vacation request...",
    
    // Case Studies
    "cases.title": "Success",
    "cases.titleHighlight": "stories",
    "cases.subtitle": "Real results from real companies",
    "cases.costs": "Costs",
    "cases.reservations": "Reservations",
    "cases.responseTime": "Response time",
    "cases.clients": "Booked clients",
    "cases.missedCalls": "Missed calls",
    "cases.satisfaction": "Satisfaction",
    "cases.sales": "Sales",
    "cases.servedClients": "Served clients",
    "cases.case1.company": "Restaurant \"Tradition\"",
    "cases.case1.industry": "Restaurant industry",
    "cases.case1.description": "Automated reservation acceptance and 24/7 question answering",
    "cases.case2.company": "Hair Salon \"Luxury Hair\"",
    "cases.case2.industry": "Personal services",
    "cases.case2.description": "AI assistant for booking appointments and customer reminders",
    "cases.case3.company": "E-shop \"TechZone\"",
    "cases.case3.industry": "E-commerce",
    "cases.case3.description": "24/7 customer support and sales assistant",
    
    // Pricing
    "pricing.title": "Plans and",
    "pricing.titleHighlight": "pricing",
    "pricing.subtitle": "Choose the plan that fits your needs",
    "pricing.noFee": "No setup fee",
    "pricing.guarantee": "30-day guarantee",
    "pricing.noContract": "No binding contract",
    "pricing.popular": "Most popular",
    "pricing.month": "month",
    "pricing.starter.name": "Starter",
    "pricing.starter.description": "Ideal for small businesses and startups",
    "pricing.starter.f1": "Up to 1000 conversations/month",
    "pricing.starter.f2": "Basic integrations",
    "pricing.starter.f3": "Email support",
    "pricing.starter.f4": "Basic AI model",
    "pricing.starter.f5": "1 voice assistant",
    "pricing.starter.cta": "Start now",
    "pricing.pro.name": "Pro",
    "pricing.pro.description": "For growing companies with high demands",
    "pricing.pro.f1": "Up to 5000 conversations/month",
    "pricing.pro.f2": "All integrations",
    "pricing.pro.f3": "Priority support",
    "pricing.pro.f4": "Personalized AI model",
    "pricing.pro.f5": "Up to 3 voice assistants",
    "pricing.pro.f6": "Advanced analytics",
    "pricing.pro.f7": "Custom voices",
    "pricing.pro.cta": "Choose Pro",
    "pricing.enterprise.name": "Enterprise",
    "pricing.enterprise.description": "For large corporations and special needs",
    "pricing.enterprise.f1": "Unlimited conversations",
    "pricing.enterprise.f2": "Dedicated infrastructure",
    "pricing.enterprise.f3": "24/7 technical support",
    "pricing.enterprise.f4": "Custom AI training",
    "pricing.enterprise.f5": "Unlimited assistants",
    "pricing.enterprise.f6": "White label solution",
    "pricing.enterprise.f7": "SLA guarantee",
    "pricing.enterprise.f8": "On-premise option",
    "pricing.enterprise.cta": "Contact us",
    
    // Contact
    "contact.title": "Ask us",
    "contact.titleHighlight": "anything",
    "contact.subtitle": "Tell us about your business and we'll create a unique AI voice for you",
    "contact.name": "Full name",
    "contact.namePlaceholder": "John Smith",
    "contact.email": "Email",
    "contact.emailPlaceholder": "john@example.com",
    "contact.phone": "Phone",
    "contact.phonePlaceholder": "+359 888 123 456",
    "contact.company": "Company",
    "contact.companyPlaceholder": "My company",
    "contact.message": "Tell us about your business",
    "contact.messagePlaceholder": "Describe your needs and how we can help...",
    "contact.submit": "Send request",
    "contact.submitting": "Sending...",
    "contact.success": "Success!",
    "contact.error": "Error",
    "contact.errorMessage": "An error occurred while sending the request",
    "contact.emailLabel": "Email",
    "contact.phoneLabel": "Phone",
    "contact.officeLabel": "Office",
    "contact.workingHours": "Working hours",
    "contact.workingHoursText": "Monday - Friday: 9:00 AM - 6:00 PM",
    "contact.aiWorkingHours": "AI assistants work 24/7",
    
    // Footer
    "footer.description": "We create voice AI assistants that work 24/7 and speak like humans.",
    "footer.products": "Products",
    "footer.voiceAssistants": "Voice assistants",
    "footer.chatbots": "Chatbots",
    "footer.integrations": "Integrations",
    "footer.analytics": "Analytics",
    "footer.company": "Company",
    "footer.aboutUs": "About us",
    "footer.clients": "Clients",
    "footer.prices": "Pricing",
    "footer.contacts": "Contacts",
    "footer.legal": "Legal information",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms of use",
    "footer.gdpr": "GDPR",
    "footer.cookies": "Cookies",
    "footer.copyright": "© 2025 Voxal. All rights reserved.",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("bg")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("voxal_language") as Language | null
    if (savedLanguage) {
      setLanguage(savedLanguage)
    }
  }, [])

  useEffect(() => {
    localStorage.setItem("voxal_language", language)
  }, [language])

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
